### PR TITLE
Update ultimateListView.js

### PR DESCRIPTION
**Pull request by wengcan**
fix problem: pagination content not in the center when the  UltimateListView  is wrapped  with some element ( such as ScrollView )

### CODE REVIEW

**Comment by gameboyVito** [comment]
Hi, @wengcan thx for your effort. The reason why I set the width of `paginationView` to be the device width is because I need to make sure the `FooterView` can be displayed on both of list and grid mode correctly. If you want to wrap this component to another component like ListView, you can customize them by passing your own component with your own styles to `emptyView`, `paginationFetchingView`, `paginationWaitingView`, `paginationAllLoadedView`
```
<UltimateListView
        ...other props
        emptyView={this.renderEmptyView}
        paginationFetchingView={this.renderPaginationFetchingView}
        paginationWaitingView={this.renderPaginationWaitingView}
        paginationAllLoadedView={this.renderPaginationAllLoadedView}
/>
```

**Comment by wengcan** [comment]
Hi @gameboyVito , seems it works well even if you don't set the width of the style in both list and grid mode

**Comment by gameboyVito** [comment]
Yes, that's because you are using the new FlatList version. If you are using the old ListView verision by setting legacyImplementation to true, this width style is important

**Comment by wengcan** [comment]
thx @gameboyVito

**Pull request closed without merging**
